# Generated by Django 5.0 on 2024-04-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tirage',
            name='tranche_age',
            field=models.IntegerField(default=60, null=True),
        ),
    ]
