# Generated by Django 5.0.2 on 2024-04-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haaj',
            name='maahram_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
