# Generated by Django 5.0.3 on 2024-05-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirage',
            name='nombre_waiting',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tirage',
            name='tirage_défini',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='winners',
            name='payement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='winners',
            name='visite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tirage',
            name='tranche_age',
            field=models.IntegerField(default=60, null=True),
        ),
    ]
