# Generated by Django 4.2.11 on 2024-05-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tirage',
            name='tranche_age',
            field=models.IntegerField(default=60, null=True),
        ),
    ]
