# Generated by Django 5.0.3 on 2024-04-23 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tirage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tirage', models.IntegerField(default=1)),
                ('nombre_de_place', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Baladiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wilaya', models.IntegerField(default=None, null=True)),
                ('id_utilisateur', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('tirage', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.tirage')),
            ],
        ),
    ]
