# Generated by Django 5.0.3 on 2024-05-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_tirage_nombre_waiting_tirage_tirage_défini_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winners',
            name='nin',
            field=models.IntegerField(unique=True),
        ),
    ]
