# Generated by Django 5.0.4 on 2024-05-08 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_tirage_tranche_age'),
        ('registration', '0003_alter_winners_nin'),
    ]

    operations = [
    ]
