# Generated by Django 5.0.4 on 2024-05-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_merge_20240508_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirage',
            name='tirage_défini',
            field=models.BooleanField(default=False),
        ),
    ]
