# Generated by Django 5.0.3 on 2024-05-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_tirage_tirage_défini'),
    ]

    operations = [
        migrations.AddField(
            model_name='baladiya',
            name='tirage_défini',
            field=models.BooleanField(default=False),
        ),
    ]
