# Generated by Django 5.0.3 on 2024-05-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_baladiya_tirage_défini'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baladiya',
            name='tirage_défini',
        ),
        migrations.AddField(
            model_name='tirage',
            name='tirage_fini',
            field=models.BooleanField(default=False),
        ),
    ]
