# Generated by Django 5.0.4 on 2024-05-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_baladiya_tirage_défini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winners',
            name='payement',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='winners',
            name='visite',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
