# Generated by Django 5.0.4 on 2024-06-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_baladiya_tirage_défini'),
    ]

    operations = [
        migrations.AddField(
            model_name='baladiya',
            name='tirage_défini',
            field=models.BooleanField(default=False),
        ),
    ]
