# Generated by Django 5.0.4 on 2024-06-05 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_winners_payement_alter_winners_visite'),
        ('registration', '0007_remove_baladiya_tirage_défini_tirage_tirage_fini'),
        ('registration', '0008_baladiya_tirage_défini'),
    ]

    operations = [
    ]
