# Generated by Django 5.0.4 on 2024-06-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_merge_20240605_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tirage',
            name='tirage_défini',
        ),
        migrations.AddField(
            model_name='baladiya',
            name='tirage_défini',
            field=models.BooleanField(default=False),
        ),
    ]
