# Generated by Django 5.0.4 on 2024-06-05 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_remove_tirage_tirage_défini_baladiya_tirage_défini'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baladiya',
            name='tirage_défini',
        ),
    ]
