# Generated by Django 5.0 on 2024-03-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='elhadj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('dateDeNaissance', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='M', max_length=1)),
            ],
        ),
    ]
