<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-04-23 13:03
=======
# Generated by Django 5.0.2 on 2024-04-22 23:48
>>>>>>> main

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_email_verified', models.BooleanField(null=True)),
                ('code', models.CharField(max_length=4, null=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('dateOfBirth', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('province', models.IntegerField(choices=[(1, 'Wilaya dAdrar'), (2, 'Wilaya de Chlef'), (3, 'Wilaya de Laghouat'), (4, 'Wilaya dOum El Bouaghi'), (5, 'Wilaya de Betna'), (6, 'Wilaya de Bejaya'), (7, 'Wilaya de Biskra'), (8, 'Wilaya de Bechar'), (9, 'Wilaya de Blida'), (10, 'Wilaya de Bouira'), (11, 'Wilaya de Tamanrasset'), (12, 'Wilaya de Tebessa'), (13, 'Wilaya de Tlemcen'), (14, 'Wilaya de Tiaret'), (15, 'Wilaya de Tizi Ouzou'), (16, 'Wilaya dAlger'), (17, 'Wilaya de Djelfa'), (18, 'Wilaya de Jijel'), (19, 'Wilaya de Setif'), (20, 'Wilaya de Saida'), (21, 'Wilaya de Skikda'), (22, ' Wilaya de SIDI Bel Abbes'), (23, 'Wilaya de Annaba'), (24, 'Wilaya de Guelma'), (25, 'Wilaya de Constantine'), (26, 'Wilaya de Medea'), (27, 'Wilaya de Mostaganem'), (28, 'Wilaya de Msila'), (29, 'Wilaya de Mascara'), (30, 'Wilaya de Ouargla'), (31, 'Wilaya de Oran'), (32, 'Wilaya de El Bayadh'), (33, 'Wilaya de Illizi'), (34, 'Wilaya de Bordj Bou Arreridj'), (35, 'Wilaya de Boumerdès'), (36, 'Wilaya de El Tarf'), (37, 'Wilaya de Tindouf'), (38, 'Wilaya de Tissemsilt'), (39, 'Wilaya de El Oued'), (40, 'Wilaya de Khenchela'), (41, 'Wilaya de Souk Ahras'), (42, 'Wilaya de Tipaza'), (43, 'Wilaya de Mila'), (44, 'Wilaya de Aïn Defla'), (45, 'Wilaya de Naâma'), (46, 'Wilaya de Aïn Témouchent'), (47, 'Wilaya de Ghardaïa'), (48, 'Wilaya de Relizane'), (49, 'Wilaya de El Mghair'), (50, 'Wilaya de El Menia'), (51, 'Wilaya de Ouled Djellal'), (52, 'Wilaya de Bordj Baji Mokhtar'), (53, 'Wilaya de Béni Abbès'), (54, 'Wilaya de Timimoun'), (55, 'Wilaya de Touggourt'), (56, 'Wilaya de Djanet'), (57, 'Wilaya de In Salah'), (58, 'Wilaya de In Guezzam')])),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=1)),
                ('nombreInscription', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="password reset's user")),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='id_role',
            field=models.ManyToManyField(to='authentication.role'),
        ),
    ]
