# Generated by Django 5.0.3 on 2024-04-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_picture',
            field=models.ImageField(default=None, null=True, upload_to='user_pictures/'),
        ),
    ]
