# Generated by Django 5.0 on 2024-03-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elhadj',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='elhadj',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
