# Generated by Django 5.0 on 2024-04-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_role',
        ),
        migrations.DeleteModel(
            name='role',
        ),
    ]
