# Generated by Django 5.0 on 2024-03-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_elhadj_email_elhadj_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='elhadj',
            new_name='user',
        ),
    ]
