# Generated by Django 5.0 on 2024-04-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_personal_picture'),
        ('registration', '0002_alter_tirage_tranche_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.AddField(
            model_name='user',
            name='baladia',
            field=models.ManyToManyField(to='registration.baladiya'),
        ),
    ]
