# Generated by Django 5.0 on 2024-04-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_city_user_baladia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='baladia',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
    ]
