# Generated by Django 5.0 on 2024-03-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_elhadj_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='elHAdj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('dateOfBirth', models.DateField()),
                ('province', models.CharField(max_length=50)),
                ('city', models.IntegerField(choices=[(1, 'Wilaya dAdrar'), (2, 'Wilaya de Chlef'), (3, 'Wilaya de Laghouat'), (4, 'Wilaya dOum El Bouaghi')])),
                ('gender', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='M', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
