# Generated by Django 5.0 on 2024-03-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_elhadj_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='elhadj',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='elhadj',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='elhadj',
            name='province',
            field=models.IntegerField(choices=[(1, 'Wilaya dAdrar'), (2, 'Wilaya de Chlef'), (3, 'Wilaya de Laghouat'), (4, 'Wilaya dOum El Bouaghi')]),
        ),
    ]
