# Generated by Django 5.0.6 on 2024-05-15 15:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_picture',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
        ),
    ]
