# Generated by Django 5.0 on 2024-03-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_elhadj_is_email_verified_alter_elhadj_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elhadj',
            name='is_email_verified',
        ),
        migrations.AlterField(
            model_name='elhadj',
            name='province',
            field=models.IntegerField(choices=[(1, 'Wilaya dAdrar'), (2, 'Wilaya de Chlef'), (3, 'Wilaya de Laghouat'), (4, 'Wilaya dOum El Bouaghi'), (5, 'Wilaya de Betna'), (6, 'Wilaya de Bejaya'), (7, 'Wilaya de Biskra'), (8, 'Wilaya de '), (9, 'Wilaya de Blida'), (10, 'Wilaya de Bouira'), (11, 'Wilaya de '), (12, 'Wilaya de Tebessa'), (13, 'Wilaya de Telemcen')]),
        ),
    ]
