# Generated by Django 5.0.2 on 2024-05-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_personal_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('administrateur', 'administrateur'), ('responsable tirage', 'responsable tirage'), ('medecin', 'medecin'), ('hedj', 'hedj'), ('banquier', 'banquier')]),
        ),
    ]
