# Generated by Django 5.0.3 on 2024-05-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_personal_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='view_tirage',
            field=models.BooleanField(default=False),
        ),
    ]
