# Generated by Django 5.0 on 2024-03-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_elhadj_options_elhadj_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elhadj',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
