# Generated by Django 5.0 on 2024-03-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_elhadj_is_email_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elhadj',
            options={},
        ),
        migrations.RemoveField(
            model_name='elhadj',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='elhadj',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='elhadj',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='elhadj',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='elhadj',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='elhadj',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='elhadj',
            name='user_permissions',
        ),
    ]
