# Generated by Django 5.0.3 on 2024-03-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_usermodel_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='User',
        ),
    ]
