# Generated by Django 5.0.3 on 2024-03-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_passwordreset_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='user_id',
            new_name='user',
        ),
    ]
