# Generated by Django 5.0 on 2024-03-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_remove_utilisateur_password_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='user',
            new_name='emailUtilisateur',
        ),
    ]
