# Generated by Django 5.0 on 2024-03-29 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_rename_user_utilisateur_emailutilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='emailUtilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
