# Generated by Django 5.0 on 2024-03-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_city_province_gestionnairetirage_emailutilisateur_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gestionnaireWilaya',
            new_name='gestionnaireProvince',
        ),
    ]
