# Generated by Django 5.0.3 on 2024-03-31 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_rename_gestionnairewilaya_gestionnaireprovince'),
    ]

    operations = [
        migrations.DeleteModel(
            name='city',
        ),
        migrations.RemoveField(
            model_name='gestionnaireprovince',
            name='emailUtilisateur',
        ),
        migrations.RemoveField(
            model_name='gestionnairetirage',
            name='emailUtilisateur',
        ),
        migrations.DeleteModel(
            name='province',
        ),
        migrations.DeleteModel(
            name='gestionnaireProvince',
        ),
        migrations.DeleteModel(
            name='gestionnaireTirage',
        ),
    ]
