# Generated by Django 5.0.3 on 2024-03-31 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0025_delete_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haaj',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.utilisateur')),
                ('first_name_arabic', models.CharField(max_length=100)),
                ('last_name_arabic', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('NIN', models.CharField(max_length=150, unique=True)),
                ('card_expiration_date', models.DateField()),
                ('passport_id', models.CharField(max_length=100)),
                ('passport_expiration_date', models.DateField()),
                ('nationality', models.CharField(choices=[('Algérienne', 'Algérienne'), ('Autre', 'Autre')])),
                ('country_of_residence', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('personal_picture', models.ImageField(upload_to='haaj_pictures/')),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.utilisateur',),
        ),
        migrations.CreateModel(
            name='Haaja',
            fields=[
                ('haaj_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Draw_Registration.haaj')),
                ('maahram_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('Draw_Registration.haaj',),
        ),
    ]
